# Site settings
title: Michael Joseph Kramer
email: michael@sage.house
bio: &bio >
  <p>Michael Joseph Kramer is a passionate software developer focusing on quality, testing, and agile practices. He's currently working with Ruby and JavaScript.</p><p>Michael is located in Columbus, OH.</p>
description: *bio
baseurl: ""
url: "http://michaeljosephkramer.com"
encoding: utf-8
twitter_username: michaelkramer
github_username:  michaeljosephkramer
linkedin_username:  michaeljosephkramer
facebook_username:  michaeljosephkramer
feedburner_username:  michaeljosephkramer
disqus_username:  michaeljosephkramer
google_analytics_id: UA-592651-4
clicky_id: 66487006

# Build settings
markdown: redcarpet
highligher: rouge
permalink: pretty
redcarpet:
  extensions: [smart]
